export const ERROR_CODES = {
    INVALID_DATA: 'INVALID_DATA',
    MEASURE_NOT_FOUND: 'MEASURE_NOT_FOUND',
    CONFIRMATION_DUPLICATE: 'CONFIRMATION_DUPLICATE',
    DOUBLE_REPORT: 'DOUBLE_REPORT',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_TYPE: 'INVALID_TYPE'
};